In [175]:
import numpy as np
import pandas as pd
import tensorflow as tf

preprocessing the data


In [176]:
dataset=pd.read_csv("Churn_Modelling.csv")
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [177]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [178]:
#lebel encoding of gender column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [179]:
#oneHOtencoding of country dataset
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [180]:
#now split dataset into training and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [181]:
#feature scalling of the x_test and x_train cause some colum are bigger in size than other
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


Building the ANN

In [182]:
#initialize the ANN
ann=tf.keras.models.Sequential()
#adding the first input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
#adding the output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

Training the ANN

In [183]:
#Compile the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
#Train the ANN on the training sets
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 673us/step - accuracy: 0.7716 - loss: 0.5886
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 483us/step - accuracy: 0.8005 - loss: 0.4868
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step - accuracy: 0.7923 - loss: 0.4619
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - accuracy: 0.8052 - loss: 0.4345
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 583us/step - accuracy: 0.8078 - loss: 0.4222
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step - accuracy: 0.8189 - loss: 0.4109
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 565us/step - accuracy: 0.8144 - loss: 0.4096
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 552us/step - accuracy: 0.8194 - loss: 0.4058
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 698us/step - accuracy: 0.8323 - loss: 0.3970
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - accuracy: 0.8441 - loss: 0.3769
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - accuracy: 0.8432 - loss: 0.3777
Epoch 12/100
250/25

In [184]:
#predict the data on x_test
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[False]]


In [185]:
#predict on our test cases
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [186]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_pred,y_test))
accuracy_score(y_pred,y_test)

[[1529  208]
 [  66  197]]


0.863